// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnO6l32d6tw4Rt_7Ku1wdMDMcmNMOm7Hc',
    appId: '1:179983668883:android:697d7fb90c8146bf3bdf66',
    messagingSenderId: '179983668883',
    projectId: 'app-uas-e4559',
    databaseURL: 'https://app-uas-e4559-default-rtdb.firebaseio.com',
    storageBucket: 'app-uas-e4559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFIYFBBKKxkt4YpA897hGdymDTbUljlA',
    appId: '1:179983668883:ios:11a8bc2e591bd3363bdf66',
    messagingSenderId: '179983668883',
    projectId: 'app-uas-e4559',
    databaseURL: 'https://app-uas-e4559-default-rtdb.firebaseio.com',
    storageBucket: 'app-uas-e4559.firebasestorage.app',
    iosClientId: '179983668883-vb70g2kna6p8mc5lpulac7eheikd4kq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appUas',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbc_EHYaS9Of_ED4kAQfWYKAyaY4Ag-Q',
    appId: '1:179983668883:web:9d2ed9d9540aeb4c3bdf66',
    messagingSenderId: '179983668883',
    projectId: 'app-uas-e4559',
    authDomain: 'app-uas-e4559.firebaseapp.com',
    databaseURL: 'https://app-uas-e4559-default-rtdb.firebaseio.com',
    storageBucket: 'app-uas-e4559.firebasestorage.app',
    measurementId: 'G-6BDJTWJE8M',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApbc_EHYaS9Of_ED4kAQfWYKAyaY4Ag-Q',
    appId: '1:179983668883:web:69b10a8593b61d573bdf66',
    messagingSenderId: '179983668883',
    projectId: 'app-uas-e4559',
    authDomain: 'app-uas-e4559.firebaseapp.com',
    databaseURL: 'https://app-uas-e4559-default-rtdb.firebaseio.com',
    storageBucket: 'app-uas-e4559.firebasestorage.app',
    measurementId: 'G-PJD13E95JE',
  );

}